site_name: Tabular
repo_url: https://github.com/leShaunj/tabular
site_url: https://leshaunj.github.io/tabular
edit_uri: ""

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      primary: custom
      scheme: linked
      toggle:
        icon: material/link
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      primary: custom
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/logo.svg
  favicon: assets/logo.svg
  icon:
    logo: logo
  features:
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.code.select

site_description: "Provide `go-cobra`-style tab-completions for your Crystal CLI."
site_author: Arian LeShaun Johnson
copyright: Copyright &copy; 2025 ALJ

extra:
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  generator: false
  version:
    provider: mike

extra_css:
  - css/mkdocstrings.css

plugins:
  - search:
      indexing: full
  - gen-files:
      scripts:
        - docs/js/stubs.py
  - mkdocstrings:
      default_handler: crystal
  - literate-nav:
      nav_file: summary.md
  - section-index

markdown_extensions:
  - admonition
  - attr_list
  - github-callouts
  - deduplicate-toc
  - def_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - toc:
      permalink: "#"

watch:
  - src
