name: Version

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Install shards
        run: shards update

      - name: Run tests
        run: crystal spec -v --fail-fast --tag version
